**1. Program to create an element-wise comparison.**

In [8]:
import numpy as np

x=np.array([3,5,1,2,3])
y=np.array([2,5,3,2,1])

print("Array A")
print(x)
print("\nArray B")
print(y)

print("\nA>B")
print(np.greater(x,y))

print("\nA>=B")
print(np.greater_equal(x,y))

print("\nA<B")
print(np.less(x,y))

print("\nA<=B")
print(np.less_equal(x,y))

Array A
[3 5 1 2 3]

Array B
[2 5 3 2 1]

A>B
[ True False False False  True]

A>=B
[ True  True False  True  True]

A<B
[False False  True False False]

A<=B
[False  True  True  True False]


**2. Program to create an array of all the even integers from 30 to 70.**

In [7]:
import numpy as np
x=np.arange(start=30, stop=71, step=2)
print(x)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


**3. Program to create a 3x3 identity matrix.**

In [9]:
import numpy as np
x=np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**4. Program to compute sum of all elements, sum of each column and sum of
each row.**

In [13]:
import numpy as np
x=np.array([[1,0],[0,1]])
print("Array")
print(x)
print("\nSum of all elements")
print(np.sum(x))
print("\nSum of each column")
print(np.sum(x, axis=0))
print("\nSum of each row")
print(np.sum(x, axis=1))

Array
[[1 0]
 [0 1]]

Sum of all elements
2

Sum of each column
[1 1]

Sum of each row
[1 1]


**5. Program to check whether two arrays are equal (element wise) or not.**

In [14]:
import numpy as np
nums1=np.array([2,2,3,2,1])
nums2=np.array([2,3,4,3,1])
print("Original arrays:")
print(nums1)
print(nums2)
print("\nTest said two arrays are equal (element wise) or not:?")
print(nums1==nums2)
print(np.equal(nums1,nums2))

Original arrays:
[2 2 3 2 1]
[2 3 4 3 1]

Test said two arrays are equal (element wise) or not:?
[ True False False False  True]
[ True False False False  True]


**6. Program to multiply two given arrays of same size element-by-element.**

In [18]:
import numpy as np
nums1=np.array([[2,5,2],[1,5,5]])
nums2=np.array([[5,3,4],[3,2,5]])
print("Array1:")
print(nums1)
print("Array2:")
print(nums2)
print("Multiplied Array:")
print(np.multiply(nums1,nums2))

Array1:
[[2 5 2]
 [1 5 5]]
Array2:
[[5 3 4]
 [3 2 5]]
Multiplied Array:
[[10 15  8]
 [ 3 10 25]]
